/* GENERATED by scripts/build-pages.mjs from site.config.json — do not edit. */
window.JP_CONFIG = {
  "siteUrl": "https://jolly-panda-works.github.io/web",
  "mainSiteUrl": "https://jollypanda.ir/",
  "contactEmail": "sales@jollypanda.ir",
  "email": {
    "provider": "emailjs",
    "serviceId": "YOUR_EMAILJS_SERVICE_ID",
    "publicKey": "YOUR_EMAILJS_PUBLIC_KEY",
    "studioTemplateId": "YOUR_STUDIO_TEMPLATE_ID",
    "confirmTemplateId": "YOUR_CONFIRMATION_TEMPLATE_ID"
  }
};
