/* GENERATED by scripts/build-pages.mjs from site.config.json — do not edit. */
window.JP_CONFIG = {
  "siteUrl": "https://web.jollypanda.ir",
  "mainSiteUrl": "https://jollypanda.ir/",
  "contactEmail": "sales@jollypanda.ir",
  "email": {
    "provider": "emailjs",
    "serviceId": "service_6egsj2n",
    "publicKey": "5aW25Z91EWICPCbil",
    "studioTemplateId": "template_te8hqqm",
    "confirmTemplateId": "template_9bs4k5x"
  },
  "signatureUrl": "https://web.jollypanda.ir/assets/signature/usef-farahmand.png"
};
